import assert from "node:assert/strict";
import test from "node:test";
import type {MediaArtifact, ProviderJob, TtsGenerationPlan, TtsGenerationResult} from "@vpf/domain";
import {SqliteTtsRuntimeRepository} from "../src/tts-runtime.js";

const now="2026-09-10T08:00:00.000Z";
function ttsPlan():TtsGenerationPlan{return {id:"plan-1",projectId:"p1",revision:1,lifecycleStatus:"ACTIVE",createdAt:now,updatedAt:now,sourceScriptId:"script-1",sourceScriptRevision:1,sourceScriptSha256:"a".repeat(64),contentFormat:"LONGFORM",provider:"ELEVENLABS",endpoint:"/v1/text-to-speech/{voice_id}/with-timestamps",apiKeyEnv:"ELEVENLABS_API_KEY",voiceIdResolution:"VOICE_PRESET_THEN_ENV",voiceIdFallbackEnv:"ELEVENLABS_VOICE_ID",voicePreset:"HISTORY_MYSTERY_LONGFORM",modelId:"eleven_v3",outputFormat:"mp3_44100_128",maxChunkCharacters:4000,configuredVoiceSettings:{stability:.62,similarityBoost:.8,style:.04,speed:1,useSpeakerBoost:true},effectiveVoiceSettings:{stability:.62,style:.04},droppedVoiceSettings:["similarity_boost","speed","use_speaker_boost"],preserveProviderCadence:true,chunks:[{index:1,text:"테스트",textCharacterCount:3,outputRelativePath:"03_tts/chunks/chunk_001.mp3"}],outputPaths:{narration:"03_tts/narration.mp3",characterAlignment:"03_tts/character_alignment.json",metadata:"03_tts/tts_metadata.json",resolvedVoiceProfile:"03_tts/resolved_voice_profile.json"},status:"READY"};}
function event(id:string){return {event:{eventId:`evt-${id}`,projectId:"p1",eventType:`TEST_${id}`,targetType:"PROJECT" as const,targetId:"p1",trigger:"WORKFLOW_ENGINE" as const,payload:{},createdAt:now},outbox:{outboxId:`outbox-${id}`,eventId:`evt-${id}`,status:"PENDING" as const,attempts:0,createdAt:now}};}

test("SqliteTtsRuntimeRepository persists an initial AUDIO-target ProviderJob and exposes current TTS target revision",async()=>{
  const repo=new SqliteTtsRuntimeRepository(":memory:");try{const plan=ttsPlan();await repo.commitTtsPlan({previousPlan:null,nextPlan:plan,...event("plan")});const job:ProviderJob={id:"job-1",projectId:"p1",revision:1,lifecycleStatus:"ACTIVE",createdAt:now,updatedAt:now,jobType:"TTS_GENERATION",provider:"ELEVENLABS",providerProfileVersion:"1.0.0",targetType:"AUDIO",targetId:plan.id,targetRevision:plan.revision,executionMode:"AUTOMATED",status:"READY",attempt:1,inputPayload:{safe:true},resultMediaIds:[]};await repo.commitTtsProviderJob({job,...event("job")});const stored=await repo.getLatestTtsProviderJob("p1",plan.id);assert.equal(stored?.id,job.id);assert.equal(stored?.targetType,"AUDIO");assert.equal(await repo.getCurrentTargetRevision({projectId:"p1",targetType:"AUDIO",targetId:plan.id}),1);}finally{repo.close();}
});

test("TTS completion adopts an already-ingested narration MediaArtifact without duplicate insert",async()=>{
  const repo=new SqliteTtsRuntimeRepository(":memory:");try{const plan=ttsPlan();await repo.commitTtsPlan({previousPlan:null,nextPlan:plan,...event("plan2")});const media:MediaArtifact={id:"media-1",projectId:"p1",revision:1,lifecycleStatus:"ACTIVE",createdAt:now,updatedAt:now,mediaType:"AUDIO",relativePath:"03_tts/narration.mp3",mimeType:"audio/mpeg",durationMs:1000,checksum:"b".repeat(64),sourceJobId:"job-1",mediaStatus:"AVAILABLE"};
  repo.db.prepare(`INSERT INTO media_artifacts (id, project_id, revision, lifecycle_status, media_type, relative_path, mime_type, width, height, duration_ms, checksum, source_job_id, media_status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)` ).run(media.id,media.projectId,media.revision,media.lifecycleStatus,media.mediaType,media.relativePath,media.mimeType,null,null,media.durationMs,media.checksum,media.sourceJobId,media.mediaStatus,media.createdAt,media.updatedAt);
  const nextPlan:TtsGenerationPlan={...plan,revision:2,updatedAt:now,status:"COMPLETE"};const result:TtsGenerationResult={id:"result-1",projectId:"p1",revision:1,lifecycleStatus:"ACTIVE",createdAt:now,updatedAt:now,planId:plan.id,planRevision:2,sourceScriptId:plan.sourceScriptId,sourceScriptRevision:plan.sourceScriptRevision,sourceScriptSha256:plan.sourceScriptSha256,provider:"ELEVENLABS",modelId:"eleven_v3",voiceId:"REDACTED",outputFormat:"mp3_44100_128",requestIds:["req-1"],audioMediaId:media.id,audioRelativePath:"03_tts/narration.mp3",audioSha256:"b".repeat(64),audioDurationMs:1000,characterAlignmentRelativePath:"03_tts/character_alignment.json",characterAlignmentSha256:"c".repeat(64),metadataRelativePath:"03_tts/tts_metadata.json",chunkCount:1,completedAt:now};await repo.commitTtsResult({previousPlan:plan,nextPlan,previousResult:null,result,audioMedia:media,...event("complete")});const count=repo.db.prepare("SELECT COUNT(*) AS n FROM media_artifacts WHERE id = ?").get(media.id) as {n:number};assert.equal(count.n,1);assert.equal((await repo.getLatestTtsResult("p1"))?.audioMediaId,media.id);assert.equal((await repo.getLatestTtsPlan("p1"))?.status,"COMPLETE");}finally{repo.close();}
});
