import type {EditProject} from "../editorTypes";
import {staticFile} from "remotion";

declare global {interface Window {__VPF_EDITOR_API_BASE__?:string}}
export type EditorProductionIssue={code:string;message:string;data?:Record<string,unknown>};
export type SubtitleSyncProposal={id:string;text:string;currentStartFrame:number;currentDurationInFrames:number;suggestedStartFrame:number;suggestedDurationInFrames:number;deltaFrames:number;confidence:number;status:"READY"|"LOW_CONFIDENCE"|"LOCKED"};
export type SubtitleSyncPreview={model:string;language:string;modelAlignmentConfidence:number;distance:number;proposals:SubtitleSyncProposal[]};
type Envelope={success:boolean;projectId?:string;project?:EditProject;path?:string;savedAt?:string;status?:string;projectSha256?:string;outputPath?:string;errors?:EditorProductionIssue[];warnings?:EditorProductionIssue[];error?:string;model?:string;language?:string;modelAlignmentConfidence?:number;distance?:number;proposals?:SubtitleSyncProposal[];changes?:number;backupPath?:string};

const DEFAULT_LOCAL_EDITOR_API_BASE="http://127.0.0.1:4318";
export type StudioProjectConnection={projectId?:string;apiBase?:string;durationInFrames?:number};
export const configuredStudioProjectConnection=():StudioProjectConnection=>{
  if(typeof window==="undefined")return {};
  const query=new URLSearchParams(window.location.search);
  const projectId=query.get("vpfProject")?.trim()||undefined;
  const explicitBase=query.get("vpfEditorApi")?.trim()||window.__VPF_EDITOR_API_BASE__;
  const isLocalHost=window.location.hostname==="localhost"||window.location.hostname==="127.0.0.1";
  const apiBase=(explicitBase||(isLocalHost?DEFAULT_LOCAL_EDITOR_API_BASE:undefined))?.replace(/\/$/,"")||undefined;
  const frames=Number(query.get("vpfFrames"));
  return {projectId,apiBase,...(Number.isSafeInteger(frames)&&frames>0?{durationInFrames:frames}:{})};
};
const configuredBase=()=>configuredStudioProjectConnection().apiBase;
export const hasEditorPersistenceAdapter=()=>Boolean(configuredBase());
type ActiveEditorConnection={schemaVersion:1;projectId:string;apiBase:string};
const isLoopbackApiBase=(value:string)=>/^http:\/\/(?:127\.0\.0\.1|localhost):\d+$/u.test(value);
const loadActiveEditorConnection=async(options?:{signal?:AbortSignal}):Promise<ActiveEditorConnection|null>=>{try{const response=await fetch(staticFile("vpf-active-editor-connection.json"),{cache:"no-store",signal:options?.signal});if(!response.ok)return null;const connection=await response.json() as ActiveEditorConnection;if(connection?.schemaVersion!==1||typeof connection.projectId!=="string"||typeof connection.apiBase!=="string"||!isLoopbackApiBase(connection.apiBase))return null;return{...connection,apiBase:connection.apiBase.replace(/\/$/,"")};}catch{return null;}};
export const resolveEditorApiBase=async(projectId?:string,options?:{signal?:AbortSignal}):Promise<string|undefined>=>{const active=await loadActiveEditorConnection(options);if(active&&(!projectId||active.projectId===projectId))return active.apiBase;return configuredBase();};
const parse=async(response:Response)=>{const payload=await response.json() as Envelope;if(!response.ok||!payload.success)throw new Error(payload.error??`Editor persistence failed (${response.status})`);return payload;};
export const loadActiveEditorProject=async(options?:{signal?:AbortSignal}):Promise<EditProject|null>=>{const connection=configuredStudioProjectConnection();const base=await resolveEditorApiBase(connection.projectId,options);if(!base)return null;const response=await fetch(`${base}/api/editor/active`,{signal:options?.signal});if(response.status===404)return null;const payload=await parse(response);if(!payload.project)throw new Error("Active editor project payload is missing");return payload.project;};
export const loadStudioRenderProject=async(options?:{signal?:AbortSignal}):Promise<EditProject|null>=>{try{const response=await fetch(staticFile("vpf-active-editor-project.json"),{cache:"no-store",signal:options?.signal});if(response.status===404)return null;if(!response.ok)throw new Error(`Studio render snapshot failed (${response.status})`);const project=await response.json() as EditProject;if(project?.schemaVersion!==1||!project.project||!Array.isArray(project.items)||!Array.isArray(project.tracks))throw new Error("Studio render snapshot is invalid");return project;}catch(error){if(error instanceof TypeError)return null;throw error;}};
export const loadPersistedEditorProject=async(projectId:string):Promise<EditProject|null>=>{const base=await resolveEditorApiBase(projectId);if(!base)return null;const response=await fetch(`${base}/api/editor/project/${encodeURIComponent(projectId)}`);if(response.status===404)return null;const payload=await parse(response);if(!payload.project)throw new Error("Saved editor project payload is missing");return payload.project;};
const requireResolvedBase=async(projectId:string)=>{const base=await resolveEditorApiBase(projectId);if(!base)throw new Error("Unified editor persistence is not bound. Start editor:studio-server and reopen Studio.");return base;};
export const savePersistedEditorProject=async(project:EditProject):Promise<{path:string;savedAt:string}>=>{const base=await requireResolvedBase(project.project.id);const response=await fetch(`${base}/api/editor/project/${encodeURIComponent(project.project.id)}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(project)});const payload=await parse(response);return{path:payload.path??"",savedAt:payload.savedAt??new Date().toISOString()};};
export const previewSubtitleAudioSync=async(project:EditProject):Promise<SubtitleSyncPreview>=>{const base=await requireResolvedBase(project.project.id);const response=await fetch(`${base}/api/editor/project/${encodeURIComponent(project.project.id)}/subtitle-sync/preview`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(project)});const payload=await parse(response);if(!payload.model||!payload.language||!payload.proposals)throw new Error("Subtitle sync preview payload is incomplete");return{model:payload.model,language:payload.language,modelAlignmentConfidence:payload.modelAlignmentConfidence??0,distance:payload.distance??0,proposals:payload.proposals};};
export const promoteSubtitleAudioSync=async(project:EditProject):Promise<{changes:number;backupPath:string;project:EditProject}>=>{const base=await requireResolvedBase(project.project.id);const response=await fetch(`${base}/api/editor/project/${encodeURIComponent(project.project.id)}/subtitle-sync/commit`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(project)});const payload=await parse(response);if(!payload.project)throw new Error("Canonical promotion did not return the refreshed editor project");return{changes:Number(payload.changes??0),backupPath:payload.backupPath??"",project:payload.project};};
const production=async(projectId:string,action:"gate"|"render")=>{const base=await requireResolvedBase(projectId);const response=await fetch(`${base}/api/editor/project/${encodeURIComponent(projectId)}/${action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({allowRemote:false,allowVisualGaps:false})});return parse(response);};
export const runEditorProductionGate=(projectId:string)=>production(projectId,"gate");
export const runEditorFinalRender=(projectId:string)=>production(projectId,"render");
export const assertCompatibleEditorProject=(initial:EditProject,loaded:EditProject)=>{if(initial.schemaVersion!==1||loaded.schemaVersion!==1)throw new Error("Only Generic Editor schemaVersion 1 is supported");if(initial.project.id!==loaded.project.id)throw new Error(`Saved project id mismatch: ${loaded.project.id}`);for(const key of ["fps","width","height","durationInFrames"] as const){if(initial.project[key]!==loaded.project[key])throw new Error(`Saved project ${key} does not match the current composition`);}};
