import {useRef,useState} from "react";
import type {DragEvent,FC, PointerEvent as ReactPointerEvent} from "react";
import {editorActions} from "../editorActions";
import {isAudioTimelineItem} from "../audioSplitCommand";
import {selectItemsForTrack} from "../editorSelectors";
import type {TimelineItem} from "../editorTypes";
import {useStudioEditor} from "../StudioEditorContext";
import {buildSnapTargets,resolveSnapDelta} from "../snapEngine";
import type {SnapTarget} from "../snapEngine";
import {AudioWaveform} from "../audio/AudioWaveform";

const color=(type:string)=>type==="VIDEO"?"#315f8f":type==="IMAGE"?"#547b51":["TTS","CLIP_AUDIO"].includes(type)?"#7a4e91":type==="BGM"?"#8b6a35":type==="SFX"?"#9b4f4a":type==="SUBTITLE"?"#336f73":type==="TEXT"?"#596f7c":"#6d6258";
type DragMode="move"|"trim-start"|"trim-end";
type Drag={item:TimelineItem;mode:DragMode;pointerId:number;startClientX:number;appliedFrames:number};

type TimelineProps={currentFrame:number;onSeek:(frame:number)=>void;onZoomByFactor:(factor:number)=>void;canSplitAudio:boolean;onSplitAudio:()=>void;canSplitVideo:boolean;onSplitVideo:()=>void};

export const Timeline:FC<TimelineProps>=({currentFrame,onSeek,onZoomByFactor,canSplitAudio,onSplitAudio,canSplitVideo,onSplitVideo})=>{
  const {state,dispatch}=useStudioEditor();const zoom=Math.max(.05,state.project.settings.timelineZoom);const ppf=Math.max(.12,.45*zoom);const total=state.project.project.durationInFrames;
  const drag=useRef<Drag|null>(null);
  const [snapGuide,setSnapGuide]=useState<SnapTarget|null>(null);
  const beginDrag=(event:ReactPointerEvent<HTMLElement>,item:TimelineItem,mode:DragMode)=>{if(item.locked)return;event.preventDefault();event.stopPropagation();event.currentTarget.setPointerCapture(event.pointerId);drag.current={item,mode,pointerId:event.pointerId,startClientX:event.clientX,appliedFrames:0};setSnapGuide(null);dispatch(editorActions.selectItem([item.id]));dispatch(editorActions.beginEditTransaction());};
  const moveDrag=(event:ReactPointerEvent<HTMLDivElement>)=>{const active=drag.current;if(!active||active.pointerId!==event.pointerId)return;const rawDesired=Math.round((event.clientX-active.startClientX)/ppf);const snapped=resolveSnapDelta({item:active.item,mode:active.mode,rawDeltaFrames:rawDesired,targets:buildSnapTargets(state,active.item.id),toleranceFrames:state.project.settings.snapToleranceFrames,enabled:state.project.settings.snapEnabled,bypass:event.shiftKey});const desired=snapped.deltaFrames;setSnapGuide(snapped.target);if(desired===active.appliedFrames)return;const delta=desired-active.appliedFrames;active.appliedFrames=desired;if(active.mode==="move")dispatch(editorActions.moveItem(active.item.id,Math.max(0,active.item.timelineStartFrame+desired)));else if(active.mode==="trim-start")dispatch(editorActions.trimItemStart(active.item.id,delta));else dispatch(editorActions.trimItemEnd(active.item.id,delta));};
  const endDrag=(event:ReactPointerEvent<HTMLDivElement>)=>{if(drag.current?.pointerId!==event.pointerId)return;drag.current=null;setSnapGuide(null);dispatch(editorActions.endEditTransaction());};
  const isTimelineDraggable=(item:TimelineItem)=>item.type==="VIDEO"||item.type==="IMAGE"||item.type==="SUBTITLE"||item.type==="TTS"||item.type==="BGM"||item.type==="SFX";
  const handleStyle=(side:"left"|"right")=>({position:"absolute" as const,[side]:0,top:0,bottom:0,width:8,cursor:"ew-resize",zIndex:2});
  const allowAudioDrop=(event:DragEvent<HTMLDivElement>)=>{if(event.dataTransfer.types.includes("application/x-vpf-audio-item"))event.preventDefault();};
  const dropAudio=(event:DragEvent<HTMLDivElement>)=>{const sourceId=event.dataTransfer.getData("application/x-vpf-audio-item");const source=state.project.items.find((item)=>item.id===sourceId);const trackId=(event.target as HTMLElement).closest<HTMLElement>("[data-editor-track]")?.dataset.editorTrack;if(!source||(source.type!=="BGM"&&source.type!=="SFX")||!trackId)return;const track=state.project.tracks.find((candidate)=>candidate.id===trackId);if(track?.type!=="AUDIO")return;event.preventDefault();const bounds=event.currentTarget.getBoundingClientRect();const rawFrame=Math.max(0,Math.round((event.clientX-bounds.left+event.currentTarget.scrollLeft-140)/ppf));const snap=resolveSnapDelta({item:{...source,timelineStartFrame:rawFrame},mode:"trim-start",rawDeltaFrames:0,targets:buildSnapTargets(state),toleranceFrames:state.project.settings.snapToleranceFrames,enabled:state.project.settings.snapEnabled,bypass:event.shiftKey});const frame=Math.max(0,rawFrame+snap.deltaFrames);dispatch(editorActions.duplicateItem(source.id,`audio-${source.type.toLowerCase()}-${crypto.randomUUID()}`,frame,trackId));};
  return <div data-editor-timeline="true" onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={endDrag} onDragOver={allowAudioDrop} onDrop={dropAudio} style={{overflow:"auto",maxHeight:250,background:"#101215",borderTop:"1px solid #333",fontFamily:"sans-serif",fontSize:11,color:"white",touchAction:"none"}}>
    <div style={{position:"sticky",left:0,zIndex:20,display:"flex",gap:6,padding:6,background:"#17191c"}}><button onClick={()=>onZoomByFactor(1/1.2)}>-</button><span>zoom {zoom.toFixed(2)}x</span><button onClick={()=>onZoomByFactor(1.2)}>+</button><button data-editor-command="toggle-snap" aria-pressed={state.project.settings.snapEnabled} onClick={()=>dispatch(editorActions.setSnap(!state.project.settings.snapEnabled))}>Snap {state.project.settings.snapEnabled?"On":"Off"}</button><span>{state.project.settings.snapToleranceFrames}f</span><button data-editor-command="split-audio" disabled={!canSplitAudio} onClick={onSplitAudio} title="Split selected audio at playhead (S)">Split Audio</button><button data-editor-command="split-video" disabled={!canSplitVideo} onClick={onSplitVideo} title="Split selected video at playhead (S)">Razor Video</button><input aria-label="playhead" type="range" min={0} max={Math.max(0,total-1)} value={Math.min(currentFrame,total-1)} onChange={(e)=>onSeek(Number(e.currentTarget.value))} style={{flex:1}}/><span>F{currentFrame}</span></div>
    <div style={{minWidth:Math.max(900,total*ppf+150),position:"relative"}}>{snapGuide?<div data-editor-snap-guide={snapGuide.kind} title={`${snapGuide.kind} · F${snapGuide.frame}`} style={{position:"absolute",left:140+snapGuide.frame*ppf,top:0,bottom:0,width:1,background:"#ffd65a",zIndex:19,pointerEvents:"none"}}/>:null}{state.project.tracks.slice().sort((a,b)=>a.order-b.order).map((track)=><div key={track.id} data-editor-track={track.id} style={{height:42,position:"relative",borderTop:"1px solid rgba(255,255,255,.08)"}}><div style={{position:"sticky",left:0,zIndex:10,width:130,height:42,display:"flex",alignItems:"center",paddingLeft:8,background:"#17191c"}}>{track.id} · {track.name}</div>{selectItemsForTrack(state,track.id).map((item)=>{const movable=isTimelineDraggable(item);const itemWidth=Math.max(10,item.durationInFrames*ppf);const audio=isAudioTimelineItem(item);return <button key={item.id} data-editor-timeline-item={item.id} onPointerDown={(event)=>movable&&beginDrag(event,item,"move")} onClick={()=>dispatch(editorActions.selectItem([item.id]))} onDoubleClick={()=>onSeek(item.timelineStartFrame)} style={{position:"absolute",left:140+item.timelineStartFrame*ppf,top:5,width:itemWidth,height:32,overflow:"hidden",whiteSpace:"nowrap",textOverflow:"ellipsis",border:state.selectedItemIds.includes(item.id)?"2px solid white":"1px solid #aaa",borderRadius:4,background:color(item.type),color:"white",cursor:movable?"grab":"pointer"}}>{movable&&<><span data-editor-trim-handle="start" aria-label={`${item.id} start trim`} onPointerDown={(event)=>beginDrag(event,item,"trim-start")} style={handleStyle("left")}/><span data-editor-trim-handle="end" aria-label={`${item.id} end trim`} onPointerDown={(event)=>beginDrag(event,item,"trim-end")} style={handleStyle("right")}/></>}{audio?<AudioWaveform item={item} width={itemWidth}/>:null}<span style={{position:"relative",zIndex:1}}>{item.type} · {item.id}</span></button>;})}</div>)}</div>
  </div>;
};
