import type {CSSProperties,FC} from "react";
import {editorActions} from "../editorActions";
import {selectPrimaryItem} from "../editorSelectors";
import {canSplitSubtitleAtFrame,createSubtitleSplitId,nextSubtitleForMerge,subtitleNudgeTarget,subtitleWarning} from "../subtitleSyncCommand";
import {useStudioEditor} from "../StudioEditorContext";
import type {VideoSourceUsagePolicy} from "../editorTypes";
import {videoCanonicalWindow,videoSourceOutFrame,videoSourceProvenanceLabel,videoSourceUsePercent} from "../videoSourceInfo";

const field={width:90} as const;
const panelStyle:CSSProperties={padding:"6px 8px",color:"white",fontFamily:"sans-serif",fontSize:12,display:"flex",flexWrap:"wrap",gap:8,alignItems:"center",borderTop:"1px solid #333",background:"#14171a",maxHeight:132,overflow:"auto"};
const titleStyle:CSSProperties={maxWidth:340,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"};
const textAreaStyle:CSSProperties={width:280,height:38,resize:"vertical"};

export const Inspector:FC=()=>{
  const {state,dispatch}=useStudioEditor();
  const item=selectPrimaryItem(state);
  if(!item)return <aside data-editor-inspector style={{...panelStyle,color:"#bbb"}}>Select a timeline item.</aside>;
  const subtitle=item.type==="SUBTITLE"?item:null;
  const video=item.type==="VIDEO"?item:null;
  const nextSubtitle=subtitle?nextSubtitleForMerge(state,subtitle):null;
  const warning=subtitle?subtitleWarning(state,subtitle):null;
  const canonical=video?videoCanonicalWindow(video):null;
  const splitSubtitle=()=>{if(!canSplitSubtitleAtFrame(subtitle,state.playheadFrame)||subtitle===null)return;dispatch(editorActions.splitSubtitleItem(subtitle.id,state.playheadFrame,createSubtitleSplitId(state)));};
  const nudge=(delta:number)=>{if(subtitle===null||subtitle.locked)return;dispatch(editorActions.moveItem(subtitle.id,subtitleNudgeTarget(state,subtitle,delta)));};
  return <aside data-editor-inspector style={panelStyle}>
    <strong style={titleStyle}>{item.type} · {item.id}</strong>
    <label>Start <input style={field} type="number" value={item.timelineStartFrame} onChange={(e)=>dispatch(editorActions.moveItem(item.id,Number(e.currentTarget.value)))}/></label>
    <label>Duration <input style={field} type="number" min={1} value={item.durationInFrames} onChange={(e)=>dispatch(editorActions.changeItemDuration(item.id,Number(e.currentTarget.value)))}/></label>
    {(item.type==="VIDEO"||["TTS","CLIP_AUDIO","BGM","SFX"].includes(item.type))&&"volume" in item?<label>Volume <input style={field} type="number" min={0} step={.05} value={item.volume} onChange={(e)=>dispatch(editorActions.changeVolume(item.id,Number(e.currentTarget.value)) )}/></label>:null}
    {video?<><span data-editor-video-provenance>{videoSourceProvenanceLabel(video)}</span><label>Source policy <select data-editor-source-policy value={video.sourceUsagePolicy??"QC_TRIM"} onChange={(e)=>dispatch(editorActions.changeVideoSourcePolicy(video.id,e.currentTarget.value as VideoSourceUsagePolicy))}><option value="QC_TRIM">QC Trim</option><option value="DESIGNED_DURATION">Designed duration</option><option value="FULL_SOURCE">Full source</option></select></label>{video.sourceWindowApprovalRequired?<span data-editor-source-approval-required style={{color:"#ff8c8c"}}>Re-approval required; canonical window retained</span>:null}<label>Source In <input style={field} type="number" min={0} max={Math.max(0,video.sourceAssetDurationInFrames-1)} value={video.sourceStartFrame} onChange={(e)=>dispatch(editorActions.changeVideoSourceWindow(video.id,Number(e.currentTarget.value),video.sourceDurationInFrames))}/></label><label>Source Out <input style={field} type="number" min={video.sourceStartFrame+1} max={video.sourceAssetDurationInFrames} value={videoSourceOutFrame(video)} onChange={(e)=>dispatch(editorActions.changeVideoSourceWindow(video.id,video.sourceStartFrame,Number(e.currentTarget.value)-video.sourceStartFrame))}/></label><span>Asset {video.sourceAssetDurationInFrames}f</span><span>Used {video.sourceDurationInFrames}f ({videoSourceUsePercent(video).toFixed(1)}%)</span><span>Timeline {video.durationInFrames}f</span><span>Rate {video.playbackRate.toFixed(3)}x</span>{canonical?<span data-editor-canonical-source-window>Canonical {canonical.start}–{canonical.end}f</span>:null}</>:null}
    {(item.type==="TEXT"||item.type==="SUBTITLE")?<textarea style={textAreaStyle} value={item.text} onChange={(e)=>dispatch(editorActions.updateText(item.id,e.currentTarget.value) )}/>:null}
    {subtitle?<><button data-editor-command="split-subtitle" disabled={!canSplitSubtitleAtFrame(subtitle,state.playheadFrame)} onClick={splitSubtitle}>Split subtitle</button><button data-editor-command="merge-subtitle-next" disabled={nextSubtitle===null||subtitle.locked||nextSubtitle?.locked===true} onClick={()=>nextSubtitle&&dispatch(editorActions.mergeSubtitleItems(subtitle.id,nextSubtitle.id))}>Merge next</button><button onClick={()=>nudge(-5)}>-5f</button><button onClick={()=>nudge(-1)}>-1f</button><button onClick={()=>nudge(1)}>+1f</button><button onClick={()=>nudge(5)}>+5f</button>{warning?.overlap?<span data-editor-subtitle-warning="overlap" style={{color:"#ffb36b"}}>Subtitle overlap</span>:null}{warning?.safeZone?<span data-editor-subtitle-warning="safe-zone" style={{color:"#ff8c8c"}}>Safe-zone warning</span>:null}</>:null}
    {item.type==="SUBTITLE"?<><label>Size <input style={field} type="number" min={12} value={item.fontSize} onChange={(e)=>dispatch(editorActions.updateSubtitleStyle(item.id,{fontSize:Math.max(12,Number(e.currentTarget.value))}))}/></label><label>Text color <input type="color" value={item.color} onChange={(e)=>dispatch(editorActions.updateSubtitleStyle(item.id,{color:e.currentTarget.value}))}/></label><label>Outline <input type="color" value={item.strokeColor} onChange={(e)=>dispatch(editorActions.updateSubtitleStyle(item.id,{strokeColor:e.currentTarget.value}))}/></label><label>Outline px <input style={field} type="number" min={0} max={12} value={item.strokeWidth} onChange={(e)=>dispatch(editorActions.updateSubtitleStyle(item.id,{strokeWidth:Math.max(0,Number(e.currentTarget.value))}))}/></label><label><input type="checkbox" checked={item.backgroundEnabled} onChange={(e)=>dispatch(editorActions.updateSubtitleStyle(item.id,{backgroundEnabled:e.currentTarget.checked}))}/> Highlight band</label>{item.backgroundEnabled?<><label>Band <input type="color" value={item.backgroundColor} onChange={(e)=>dispatch(editorActions.updateSubtitleStyle(item.id,{backgroundColor:e.currentTarget.value}))}/></label><label>Band opacity <input style={field} type="number" min={0} max={1} step={.05} value={item.backgroundOpacity} onChange={(e)=>dispatch(editorActions.updateSubtitleStyle(item.id,{backgroundOpacity:Math.min(1,Math.max(0,Number(e.currentTarget.value)))}))}/></label></>:null}<button onClick={()=>dispatch(editorActions.updateSubtitleStyle(item.id,{color:"#FFE45C",strokeColor:"#17130F",strokeWidth:5,backgroundEnabled:false}))}>Yellow emphasis</button><button onClick={()=>dispatch(editorActions.updateSubtitleStyle(item.id,{color:"#FFFFFF",strokeColor:"#000000",strokeWidth:6,backgroundEnabled:true,backgroundColor:"#E5422D",backgroundOpacity:.82}))}>Strong alert</button><button onClick={()=>dispatch(editorActions.updateSubtitleStyle(item.id,{color:"#FFFFFF",strokeColor:"#17130F",strokeWidth:4,backgroundEnabled:false}))}>Reset style</button></>:null}
    {(item.type==="VIDEO"||item.type==="IMAGE")?<><label>X <input style={field} type="number" value={item.x} onChange={(e)=>dispatch(editorActions.updateTransform(item.id,{x:Number(e.currentTarget.value)}))}/></label><label>Scale <input style={field} type="number" step={.01} value={item.scale} onChange={(e)=>dispatch(editorActions.updateTransform(item.id,{scale:Number(e.currentTarget.value)}))}/></label></>:null}
    <button onClick={()=>dispatch(editorActions.deleteItem(item.id))}>Delete</button>
  </aside>;
};
