import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {dirname,resolve} from "node:path";
import {fileURLToPath} from "node:url";
import ts from "typescript";
const root=resolve(dirname(fileURLToPath(import.meta.url)),"..");
const read=(path)=>readFile(resolve(root,path),"utf8");
const importTs=async(path)=>{const source=await read(path);const output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;return import(`data:text/javascript;base64,${Buffer.from(output).toString("base64")}`);};

const video={id:"v1",type:"VIDEO",trackId:"V1",timelineStartFrame:0,durationInFrames:60,enabled:true,locked:false,src:"projects/p/media/v.mp4",sourceStartFrame:10,sourceDurationInFrames:60,sourceAssetDurationInFrames:100,playbackRate:1,volume:0,x:0,y:0,scale:1,rotation:0,opacity:1,fit:"cover"};
const tts={id:"tts1",type:"TTS",trackId:"A1",timelineStartFrame:0,durationInFrames:60,enabled:true,locked:false,src:"projects/p/media/tts.mp3",sourceStartFrame:0,sourceDurationInFrames:60,sourceAssetDurationInFrames:60,volume:1,muted:false,fadeInFrames:0,fadeOutFrames:0};
const subtitle={id:"sub1",type:"SUBTITLE",trackId:"T1",timelineStartFrame:5,durationInFrames:30,enabled:true,locked:false,text:"Persistence regression",x:540,y:1650,width:900,fontFamily:"sans-serif",fontSize:60,fontWeight:700,color:"#fff",strokeColor:"#000",strokeWidth:4,textAlign:"center",lineHeight:1.1,maxLines:2,backgroundEnabled:false,backgroundColor:"#000",backgroundOpacity:.4,generationSource:"MANUAL",generatedFromTtsIds:["tts1"]};
const project={schemaVersion:1,project:{id:"p",name:"Persistence",fps:30,width:1080,height:1920,durationInFrames:120},tracks:[{id:"V1",type:"VIDEO",name:"Video",enabled:true,locked:false,order:0},{id:"T1",type:"TEXT",name:"Subtitles",enabled:true,locked:false,order:1},{id:"A1",type:"AUDIO",name:"TTS",enabled:true,locked:false,order:2}],items:[video,tts,subtitle],settings:{snapEnabled:true,snapToleranceFrames:4,timelineZoom:1,masterVolume:1}};

test("P0-10 edit project JSON roundtrip preserves source windows, video/audio splits, subtitle timing and track controls",async()=>{const {createEditorState,editorReducer}=await importTs("src/studio/editor/editorReducer.ts");let state=createEditorState(project);state=editorReducer(state,{type:"CHANGE_VIDEO_SOURCE_WINDOW",itemId:"v1",sourceStartFrame:15,sourceDurationInFrames:50});state=editorReducer(state,{type:"SPLIT_VIDEO_ITEM",itemId:"v1",splitFrame:25,newItemId:"v1b"});state=editorReducer(state,{type:"SPLIT_AUDIO_ITEM",itemId:"tts1",splitFrame:30,newItemId:"tts1b"});state=editorReducer(state,{type:"SPLIT_SUBTITLE_ITEM",itemId:"sub1",splitFrame:15,newItemId:"sub1b"});state=editorReducer(state,{type:"MOVE_ITEM",itemId:"sub1b",timelineStartFrame:18});state=editorReducer(state,{type:"SET_TRACK_MUTED",trackId:"A1",muted:true});state=editorReducer(state,{type:"SET_TRACK_SOLO",trackId:"A1",solo:true});state=editorReducer(state,{type:"SET_TRACK_LOCKED",trackId:"V1",locked:true});const persisted=JSON.parse(JSON.stringify(state.project));const reloaded=createEditorState(persisted).project;assert.deepEqual(reloaded,state.project);const videos=reloaded.items.filter((item)=>item.type==="VIDEO").sort((a,b)=>a.timelineStartFrame-b.timelineStartFrame);assert.equal(videos.length,2);assert.equal(videos[0].sourceStartFrame+videos[0].sourceDurationInFrames,videos[1].sourceStartFrame);const subtitles=reloaded.items.filter((item)=>item.type==="SUBTITLE").sort((a,b)=>a.timelineStartFrame-b.timelineStartFrame);assert.equal(subtitles[1].timelineStartFrame,18);assert.equal(reloaded.tracks.find((track)=>track.id==="A1").muted,true);assert.equal(reloaded.tracks.find((track)=>track.id==="A1").solo,true);assert.equal(reloaded.tracks.find((track)=>track.id==="V1").locked,true);});

test("P0-10 provider hydrates on open, supports manual save/reload and debounced autosave",async()=>{const context=await read("src/studio/editor/StudioEditorContext.tsx");for(const token of ["AUTO_SAVE_DELAY_MS=600","loadPersistedEditorProject(requestedProjectId)","savePersistedEditorProject(project)","const saveProject=useCallback","const reloadProject=useCallback","window.setTimeout","state.dirty","dispatch(editorActions.loadProject(loaded))"])assert.ok(context.includes(token),`missing ${token}`);});

test("P0-10 persistence transport writes the complete EditProject derivative instead of mutating project.db",async()=>{const persistence=await read("src/studio/editor/persistence/editorPersistenceApi.ts");const server=await read("scripts/editor-studio-server.mjs");assert.match(persistence,/method:"PUT"/);assert.match(persistence,/body:JSON\.stringify\(project\)/);assert.match(server,/studio_edit_project\.json/);assert.match(server,/project\.db and the approved assembly remain unchanged/);assert.doesNotMatch(server,/INSERT\s+INTO/i);assert.doesNotMatch(server,/UPDATE\s+.*project\.db/i);});

test("P0-10 browser refresh and Studio restart reload the disk draft only when its canonical fingerprint still matches",async()=>{const server=await read("scripts/editor-studio-server.mjs");for(const token of ["referenceSha256","reviewBasePath","loadProject=async","project:await loadProject()","different canonical assembly revision","quarantineIncompatibleDraft","return referenceProject"])assert.ok(server.includes(token),`missing ${token}`);assert.match(server,/writeJson\(reviewBasePath,\{schemaVersion:1,referenceSha256\}\)/);});

test("P0-10 preview and final render remain on one ProjectRenderer contract",async()=>{const preview=await read("src/editor/GenericEditorComposition.tsx");const final=await read("src/editor/GenericFinalRender.tsx");assert.match(preview,/ProjectRenderer/);assert.match(final,/ProjectRenderer/);});
