import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {dirname,resolve} from "node:path";
import {fileURLToPath} from "node:url";
import ts from "typescript";
const root=resolve(dirname(fileURLToPath(import.meta.url)),"..");
const read=(path)=>readFile(resolve(root,path),"utf8");
const importTs=async(path)=>{const source=await read(path);const output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;return import(`data:text/javascript;base64,${Buffer.from(output).toString("base64")}`);};
const makeProject=(durationInFrames=30)=>({schemaVersion:1,project:{id:"p",name:"p",fps:30,width:1080,height:1920,durationInFrames:300},tracks:[{id:"V1",type:"VIDEO",name:"Video",enabled:true,locked:false,order:0}],items:[{id:"visual-binding-r1",type:"VIDEO",trackId:"V1",timelineStartFrame:0,durationInFrames,enabled:true,locked:false,src:"v.mp4",sourceStartFrame:20,sourceDurationInFrames:60,sourceAssetDurationInFrames:180,playbackRate:1,volume:0,x:0,y:0,scale:1,rotation:0,opacity:1,fit:"cover",canonicalSourceStartFrame:20,canonicalSourceDurationInFrames:60,sourceUsagePolicy:"QC_TRIM",sourceWindowApprovalRequired:false}],settings:{snapEnabled:true,snapToleranceFrames:4,timelineZoom:1,masterVolume:1}});

test("P0-05 FULL_SOURCE does not bypass a partial canonical approval window",async()=>{const {createEditorState,editorReducer}=await importTs("src/studio/editor/editorReducer.ts");const state=createEditorState(makeProject());const next=editorReducer(state,{type:"CHANGE_VIDEO_SOURCE_POLICY",itemId:"visual-binding-r1",policy:"FULL_SOURCE"});const item=next.project.items[0];assert.equal(item.sourceUsagePolicy,"FULL_SOURCE");assert.equal(item.sourceWindowApprovalRequired,true);assert.equal(item.sourceStartFrame,20);assert.equal(item.sourceDurationInFrames,60);});

test("P0-05 QC_TRIM restores the canonical window and clears reapproval",async()=>{const {createEditorState,editorReducer}=await importTs("src/studio/editor/editorReducer.ts");let state=createEditorState(makeProject());state={...state,project:{...state.project,items:[{...state.project.items[0],sourceStartFrame:25,sourceDurationInFrames:20,sourceWindowApprovalRequired:true}]}};const next=editorReducer(state,{type:"CHANGE_VIDEO_SOURCE_POLICY",itemId:"visual-binding-r1",policy:"QC_TRIM"}).project.items[0];assert.equal(next.sourceStartFrame,20);assert.equal(next.sourceDurationInFrames,60);assert.equal(next.sourceWindowApprovalRequired,false);});

test("P0-05 DESIGNED_DURATION applies only when it fits the canonical window",async()=>{const {createEditorState,editorReducer}=await importTs("src/studio/editor/editorReducer.ts");const safe=editorReducer(createEditorState(makeProject(30)),{type:"CHANGE_VIDEO_SOURCE_POLICY",itemId:"visual-binding-r1",policy:"DESIGNED_DURATION"}).project.items[0];assert.equal(safe.sourceDurationInFrames,30);assert.equal(safe.sourceWindowApprovalRequired,false);const blocked=editorReducer(createEditorState(makeProject(90)),{type:"CHANGE_VIDEO_SOURCE_POLICY",itemId:"visual-binding-r1",policy:"DESIGNED_DURATION"}).project.items[0];assert.equal(blocked.sourceDurationInFrames,60);assert.equal(blocked.sourceWindowApprovalRequired,true);});

test("P0-05 manual source expansion beyond canonical window is blocked and flagged",async()=>{const {createEditorState,editorReducer}=await importTs("src/studio/editor/editorReducer.ts");const state=createEditorState(makeProject());const next=editorReducer(state,{type:"CHANGE_VIDEO_SOURCE_WINDOW",itemId:"visual-binding-r1",sourceStartFrame:0,sourceDurationInFrames:180}).project.items[0];assert.equal(next.sourceStartFrame,20);assert.equal(next.sourceDurationInFrames,60);assert.equal(next.sourceWindowApprovalRequired,true);});

test("P0-05 inspector exposes all source usage policies and reapproval warning",async()=>{const src=await read("src/studio/editor/inspector/Inspector.tsx");for(const token of ["data-editor-source-policy","QC_TRIM","DESIGNED_DURATION","FULL_SOURCE","Re-approval required; canonical window retained","changeVideoSourcePolicy"])assert.match(src,new RegExp(token));});
