import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {dirname,resolve} from "node:path";
import {fileURLToPath} from "node:url";
import ts from "typescript";

const root=resolve(dirname(fileURLToPath(import.meta.url)),"..");
const read=(path)=>readFile(resolve(root,path),"utf8");
const importTs=async(path)=>{const source=await read(path);const output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;return import(`data:text/javascript;base64,${Buffer.from(output).toString("base64")}`);};

test("P1-12 clipboard captures selected items and pastes them at the playhead with regenerated ids",async()=>{const {captureEditorClipboard,buildPasteItems}=await importTs("src/studio/editor/clipboardCommands.ts");const project={schemaVersion:1,project:{id:"p",name:"p",fps:30,width:1080,height:1920,durationInFrames:300},tracks:[{id:"V1",type:"VIDEO",name:"Video",enabled:true,locked:false,order:0}],items:[{id:"v1",type:"VIDEO",trackId:"V1",timelineStartFrame:10,durationInFrames:30,enabled:true,locked:false,src:"media/v.mp4",sourceStartFrame:0,sourceDurationInFrames:30,sourceAssetDurationInFrames:30,playbackRate:1,volume:1,x:0,y:0,scale:1,rotation:0,opacity:1,fit:"cover"}],settings:{snapEnabled:true,snapToleranceFrames:4,timelineZoom:1,masterVolume:1}};const clipboard=captureEditorClipboard(project,["v1"]);assert.ok(clipboard);const pasted=buildPasteItems(project,clipboard,100,()=>"v2");assert.equal(pasted[0].id,"v2");assert.equal(pasted[0].timelineStartFrame,100);assert.equal(pasted[0].src,"media/v.mp4");});

test("P1-12 paste validates target tracks and skips locked tracks",async()=>{const {captureEditorClipboard,buildPasteItems}=await importTs("src/studio/editor/clipboardCommands.ts");const item={id:"a",type:"TEXT",trackId:"T1",timelineStartFrame:5,durationInFrames:10,enabled:true,locked:false,text:"x",x:0,y:0,width:100,fontFamily:"sans",fontSize:30,fontWeight:700,color:"#fff",strokeColor:"#000",strokeWidth:1,textAlign:"center",lineHeight:1,maxLines:1,backgroundEnabled:false,backgroundColor:"#000",backgroundOpacity:.4,textRole:"FREE_TEXT"};const project={schemaVersion:1,project:{id:"p",name:"p",fps:30,width:1080,height:1920,durationInFrames:100},tracks:[{id:"T1",type:"TEXT",name:"Text",enabled:true,locked:true,order:0}],items:[item],settings:{snapEnabled:true,snapToleranceFrames:4,timelineZoom:1,masterVolume:1}};const clipboard=captureEditorClipboard(project,["a"]);assert.ok(clipboard);assert.deepEqual(buildPasteItems(project,clipboard,20,()=>"b"),[]);});

test("P1-12 duplicate preserves relative timing and uses a defined +1 frame offset",async()=>{const {buildDuplicateItems,DUPLICATE_OFFSET_FRAMES}=await importTs("src/studio/editor/clipboardCommands.ts");assert.equal(DUPLICATE_OFFSET_FRAMES,1);const project={schemaVersion:1,project:{id:"p",name:"p",fps:30,width:1080,height:1920,durationInFrames:100},tracks:[{id:"T1",type:"TEXT",name:"Text",enabled:true,locked:false,order:0}],items:[{id:"a",type:"TEXT",trackId:"T1",timelineStartFrame:5,durationInFrames:10,enabled:true,locked:false,text:"a",x:0,y:0,width:100,fontFamily:"sans",fontSize:30,fontWeight:700,color:"#fff",strokeColor:"#000",strokeWidth:1,textAlign:"center",lineHeight:1,maxLines:1,backgroundEnabled:false,backgroundColor:"#000",backgroundOpacity:.4,textRole:"FREE_TEXT"},{id:"b",type:"TEXT",trackId:"T1",timelineStartFrame:15,durationInFrames:10,enabled:true,locked:false,text:"b",x:0,y:0,width:100,fontFamily:"sans",fontSize:30,fontWeight:700,color:"#fff",strokeColor:"#000",strokeWidth:1,textAlign:"center",lineHeight:1,maxLines:1,backgroundEnabled:false,backgroundColor:"#000",backgroundOpacity:.4,textRole:"FREE_TEXT"}],settings:{snapEnabled:true,snapToleranceFrames:4,timelineZoom:1,masterVolume:1}};const copies=buildDuplicateItems(project,["a","b"],(_,index)=>`copy-${index}`);assert.deepEqual(copies.map((item)=>item.timelineStartFrame),[6,16]);});

test("P1-12 Studio exposes copy paste duplicate buttons and Ctrl/Cmd+C V D shortcuts without replacing media refs",async()=>{const controls=await read("src/studio/editor/clipboard/ClipboardControls.tsx");for(const token of ["data-editor-command=\"copy-items\"","data-editor-command=\"paste-items\"","data-editor-command=\"duplicate-items\"","event.ctrlKey||event.metaKey","key===\"c\"","key===\"v\"","key===\"d\"","beginEditTransaction","addItem","selectItem"])assert.ok(controls.includes(token),`missing ${token}`);const studio=await read("src/studio/editor/StudioEditor.tsx");assert.match(studio,/ClipboardControls/);});
